services:
  arena:
    image: $DOCKER_IMAGE_TAG
    container_name: $DOCKER_CONTAINER_NAME
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
#      - LAUNCH_PACKAGE=$LAUNCH_PACKAGE
#      - LAUNCH_FILE=$LAUNCH_FILE
#      - ADDITIONAL_LAUNCH_PARAMS=$ADDITIONAL_LAUNCH_PARAMS
    volumes:
      # to show GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # map arena-bench repo as ros package
      - ../src/flatland_agent_spawner:/home/user/src/flatland_agent_spawner
      - ../scripts/launch-simulation.sh:/home/user/launch.sh
    # uncomment this to just start container and wait instead of launching simulation
    command: tail -f /dev/null
